on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Docs Repo
              uses: actions/checkout@v3
              with:
                  path: 'fluffyv-docs'

            - name: Clone FluffyVCore Markdown API
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  repository: 'fluffytal-es/fluffyv'
                  ref: 'gh-pages'
                  path: 'fluffyv'

            - name: 'Clean Old API Docs'
              run: |
                  rm -rf ./fluffyv-docs/docs/api/classes
                  rm -rf ./fluffyv-docs/docs/api/enums
                  rm -rf ./fluffyv-docs/docs/api/interfaces
                  rm -rf ./fluffyv-docs/docs/api/modules

            - name: 'Move New API Docs'
              run: |
                  [ ! -f ./fluffyv/classes ] || mv ./fluffyv/classes ./fluffyv-docs/docs/api/classes
                  [ ! -f ./fluffyv/enums ] || mv ./fluffyv/enums ./fluffyv-docs/docs/api/enums
                  [ ! -f /fluffyv/interfaces ] || mv ./fluffyv/interfaces ./fluffyv-docs/docs/api/interfaces
                  [ ! -f ./fluffyv/modules ] || mv ./fluffyv/modules ./fluffyv-docs/docs/api/modules

            - name: 'Install NodeJS'
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Docs
              working-directory: 'fluffyv-docs'
              run: npm install

            - name: Build Docs
              working-directory: 'fluffyv-docs'
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: fluffyv-docs/docs/.vitepress/dist
                  cname: docs.fluffytal.es
